# Document HTML files or folders of HTML files to search
# Files are relative to the CWD, not the config file itself.
docs:
- site

# Dictionary of words to ignore
dictionary:
- API
- CSS
- Changelog
- Control's
- Desaturate
- EmojiOne
- Frontmatter
- GitHub
- GitLab
- Jinja
- MERCHANTABILITY
- MdPopups
- MkDocs
- NONINFRINGEMENT
- Oct
- PNG
- PackageDev
- Plugins
- Popup
- Popups
- Popups
- PyMdown
- Pygments
- RGB
- RGBA
- Screenshot
- Sublime's
- SuperFences
- TextMate
- UML
- YAML
- builtins
- deprecations
- desaturate
- docstrings
- ebeweber
- facelessuser
- frontmatter
- frontmatter's
- gforcada
- grayscale
- inline
- linting
- matcher
- mdpopup
- mkdocs
- monospace
- namespace
- namespaced
- pha
- plugin
- plugins
- popup
- popups
- preformatted
- pycqa
- pymdown
- requesters
- squidfunk
- sublicense
- tooltips
- traceback
- tuple
- unescaping
- vendored
- versa
- whitespace

# Attributes of tags to also spell check along with tag content
attributes:
- title
- alt

# Selectors describing tags to ignore (tag, class, and/or id only)
ignores:
- code
- pre
- script
- style
- a.magiclink-compare
- a.magiclink-commit
- .MathJax_Preview
- .md-nav__link
- .md-footer-custom-text
- .md-source__repository
