-- Generated by Awesome Menu Generator
-- Based on LXMED http://lxmed.sourceforge.net/ project
module("applicationsmenu")

applicationsmenu = {}

applicationsmenu[10] = {
{[====[Doublecmd]====], [====[/home/haron/.local/bin/doublecmd]====]},
{[====[PCManFM]====], [====[pcmanfm]====]},
{[====[PCManFM as root]====], [====[gksu pcmanfm]====]},
{[====[Thunar]====], [====[thunar]====]},
{[====[Thunar as root]====], [====[gksu thunar]====]},
{[====[7-Zip FM]====], [====[7zFM]====]},
{[====[compton]====], [====[compton]====]},
{[====[dupeGuru]====], [====[dupeguru-se]====]},
{[====[Galculator]====], [====[galculator]====]},
{[====[Gis Weather]====], [====[/usr/bin/gis-weather]====]},
{[====[HP Device Manager]====], [====[hp-toolbox]====]},
{[====[Q7Z]====], [====[Q7Z.pyw]====]},
{[====[Shortcut Editor]====], [====[lxshortcut -i %f]====]},
{[====[System info]====], [====[/home/haron/.local/bin/sysinfo]====]}
}
applicationsmenu[20] = {
{[====[2D-Place]====], [====[/home/haron/bin/2D-Place]====]},
{[====[PRO100 4.42]====], [====[env WINEPREFIX="/home/haron/.wine" wine '/home/haron/lib/PRO100/pro100.exe']====]},
{[====[PRO100 5.20]====], [====[env WINEPREFIX="/home/haron/.wine" wine '/home/haron/lib/Pro100-5.20-GIV/PRO100.exe']====]}
}
applicationsmenu[30] = {
{[====[HMM3]====], [====[/home/haron/.local/bin/heroes3]====]},
{[====[StarMade]====], [====[starmade]====]}
}
applicationsmenu[40] = {
{[====[Feh]====], [====[feh %F]====]},
{[====[FontForge]====], [====[fontforge]====]},
{[====[GIMP]====], [====[gimp-2.8]====]},
{[====[Gpick]====], [====[gpick]====]},
{[====[GThumb]====], [====[gthumb]====]},
{[====[inkscape]====], [====[inkscape]====]},
{[====[Pinta]====], [====[pinta]====]},
{[====[Shutter]====], [====[shutter]====]}
}
applicationsmenu[50] = {
{[====[Firefox Web Browser]====], [====[/home/haron/.local/bin/firefox]====]},
{[====[Tor-Browser]====], [====[/home/haron/.local/bin/tor-browser]====]},
{[====[Iron Web Browser]====], [====[/usr/bin/iron]====]},
{[====[Iron (portable)]====], [====[/home/haron/.local/bin/iron]====]},
{[====[Opera Web Browser]====], [====[/home/haron/.local/bin/opera]====]},
{[====[Daily]====], [====[/home/haron/.local/bin/thunderbird]====]},
{[====[Contacts]====], [====[/home/haron/.local/bin/thunderbird -addressbook]====]},
{[====[Dropbox]====], [====[dropboxd]====]},
{[====[MEGASync]====], [====[megasync]====]},
{[====[Google Drive Indicator]====], [====[/opt/thefanclub/grive-tools/grive-indicator]====]},
{[====[Grive Setup]====], [====[/bin/bash /opt/thefanclub/grive-tools/grive-setup]====]},
{[====[NixNote]====], [====[/usr/bin/nixnote2 --newNote]====]},
{[====[Transmission Remote GUI]====], [====[/usr/bin/transmission-remote-gtk]====]},
{[====[Tixati]====], [====[tixati]====]},
{[====[Viber]====], [====[viber]====]},
{[====[Zenmap]====], [====[zenmap %F]====]},
{[====[Zenmap (as root)]====], [====[/usr/share/zenmap/su-to-zenmap.sh %F]====]},
{[====[Avahi SSH Server Browser]====], [====[/usr/bin/bssh]====]},
{[====[Avahi VNC Server Browser]====], [====[/usr/bin/bvnc]====]}
}
applicationsmenu[60] = {
{[====[Sublime Text 3 Dev]====], [====[subl3]====]},
{[====[Adobe Reader 9]====], [====[acroread]====]},
{[====[LibreOffice XSLT based filters]====], [====[libreoffice]====]},
{[====[LO New Database]====], [====[libreoffice --base]====]},
{[====[LO New Document]====], [====[libreoffice --writer]====]},
{[====[LO New Drawing]====], [====[libreoffice --draw]====]},
{[====[LO New Formula]====], [====[libreoffice --math]====]},
{[====[LO New Presentation]====], [====[libreoffice --impress]====]},
{[====[LO New Spreadsheet]====], [====[libreoffice --calc]====]},
{[====[WPS Presentation]====], [====[/usr/bin/wpp]====]},
{[====[WPS Spreadsheets]====], [====[/usr/bin/et]====]},
{[====[WPS Writer]====], [====[/usr/bin/wps]====]},
{[====[YAGF]====], [====[yagf %F]====]}
}
applicationsmenu[80] = {
{[====[CMake]====], [====[cmake-gui %f]====]},
{[====[OpenJDK Monitoring & Management Console]====], [====[/usr/bin/jconsole]====]},
{[====[OpenJDK Policy Tool]====], [====[/usr/bin/policytool]====]},
{[====[Qt Assistant]====], [====[/usr/lib/qt/bin/assistant]====]},
{[====[Qt Designer]====], [====[/usr/lib/qt/bin/designer]====]},
{[====[Qt Linguist]====], [====[/usr/lib/qt/bin/linguist]====]},
{[====[Qt QDbusViewer]====], [====[/usr/lib/qt/bin/qdbusviewer]====]},
{[====[Qt4 Assistant]====], [====[assistant-qt4]====]},
{[====[Qt4 Designer]====], [====[designer-qt4]====]},
{[====[Qt4 Linguist]====], [====[linguist-qt4]====]},
{[====[Qt4 QDbusViewer]====], [====[qdbusviewer-qt4]====]}
}
applicationsmenu[90] = {
{[====[AcetoneISO]====], [====[acetoneiso %f]====]},
{[====[Deadbeef-local]====], [====[/home/haron/.local/bin/deadbeef]====]},
{[====[Deadbeef]====], [====[deadbeef]====]},
{[====[gMTP]====], [====[gmtp]====]},
{[====[MPlayer Media Player]====], [====[mplayer %F]====]},
{[====[mpv Media Player]====], [====[mpv --no-terminal --force-window --]====]},
{[====[PornTime]====], [====[/home/haron/.local/bin/PornTime]====]},
{[====[Qt V4L2 test Utility]====], [====[qv4l2]====]},
{[====[SimpleScreenRecorder]====], [====[simplescreenrecorder --logfile]====]},
{[====[SMPlayer]====], [====[smplayer]====]},
{[====[SMPlayer YouTube Browser]====], [====[smtube]====]},
{[====[Enqueue in SMPlayer]====], [====[smplayer -add-to-playlist]====]},
{[====[SopCast Player]====], [====[sopcast-player]====]},
{[====[VLC media player]====], [====[/usr/bin/vlc --started-from-file]====]}
}
applicationsmenu[100] = {
{[====[AppSet-Qt]====], [====[/usr/bin/appset-launch.sh]====]},
{[====[Avahi Zeroconf Browser]====], [====[/usr/bin/avahi-discover]====]},
{[====[GParted]====], [====[gksu /usr/bin/gparted]====]},
{[====[GSmartControl]====], [====[/usr/bin/gsmartcontrol_polkit]====]},
{[====[Htop]====], [====[htop]====]},
{[====[Manage Printing]====], [====[/usr/bin/xdg-open http://localhost:631/]====]},
{[====[VirtualBox]====], [====[VirtualBox]====]},
{[====[UNetbootin]====], [====[/usr/bin/unetbootin_polkit]====]},
{[====[urxvt]====], [====[urxvt]====]},
{[====[urxvt (client)]====], [====[urxvtc]====]},
{[====[urxvt (tabbed)]====], [====[urxvt-tabbed]====]},
{[====[UXTerm]====], [====[uxterm]====]},
{[====[XTerm]====], [====[xterm]====]},
{[====[SystemDX]====], [====[gksu systemdx]====]},
{[====[SystemDX - Tracking journal in real-time]====], [====[gksu systemdx -tj]====]},
{[====[SystemDX - Udev Monitor]====], [====[gksu systemdx -u]====]},
{[====[PacmanXG]====], [====[gksu pacmanxg]====]}
}
applicationsmenu[110] = {
{[====[Desktop Preferences]====], [====[pcmanfm --desktop-pref]====]},
{[====[NVIDIA X Server Settings]====], [====[/usr/bin/nvidia-settings]====]},
{[====[Preferred Applications]====], [====[libfm-pref-apps]====]},
{[====[Privilege granting]====], [====[gksu-properties]====]},
{[====[Qt4 Config]====], [====[qtconfig-qt4]====]}
}

applicationsmenu[1] = {
{[====[Accessories]====], applicationsmenu[10]},
{[====[Work]====], applicationsmenu[20]},
{[====[Games]====], applicationsmenu[30]},
{[====[Graphics]====], applicationsmenu[40]},
{[====[Internet]====], applicationsmenu[50]},
{[====[Office]====], applicationsmenu[60]},
{[====[Programming]====], applicationsmenu[80]},
{[====[Sound & Video]====], applicationsmenu[90]},
{[====[System Tools]====], applicationsmenu[100]},
{[====[Preferences]====], applicationsmenu[110]}
}

passed = applicationsmenu[1]
function applicationsmenu() return passed end