-- Generated by Awesome Menu Generator
-- Based on LXMED http://lxmed.sourceforge.net/ project
module("applicationsmenu")

applicationsmenu = {}

applicationsmenu[10] = {
{[====[ALSCenter]====], [====[/opt/Almin-Soft/ALSCenter/alscenter]====]},
{[====[Archive Manager]====], [====[file-roller]====]},
{[====[Capture the current active window]====], [====[shutter --active]====]},
{[====[Character Map]====], [====[gucharmap]====]},
{[====[compton]====], [====[compton]====]},
{[====[Font Manager]====], [====[font-manager %u]====]},
{[====[Font Viewer]====], [====[/usr/libexec/font-manager/font-viewer %u]====]},
{[====[Galculator]====], [====[galculator]====]},
{[====[Google Drive Indicator]====], [====[/opt/grive-tools/grive-indicator]====]},
{[====[Grive Setup]====], [====[/bin/bash /opt/grive-tools/grive-setup]====]},
{[====[Help]====], [====[xdg-open https://support.google.com/drive]====]},
{[====[HP Device Manager]====], [====[hp-toolbox]====]},
{[====[PacmanXG]====], [====[ssx pacmanxg]====]},
{[====[PacmanXG]====], [====[kdesu ssx pacmanxg]====]},
{[====[Root Terminal]====], [====[gksu -l gnome-terminal]====]},
{[====[Search for Files or Folders]====], [====[pcmanfm-mod --find-files %F]====]},
{[====[Shortcut Editor]====], [====[lxshortcut -i %f]====]},
{[====[SystemDX]====], [====[ssx systemdx]====]},
{[====[SystemDX - Tracking journal in real-time]====], [====[ssx systemdx -tj]====]},
{[====[SystemDX - Udev Monitor]====], [====[ssx systemdx -u]====]},
{[====[Xarchiver]====], [====[xarchiver %f]====]}
}
applicationsmenu[20] = {
}
applicationsmenu[30] = {
{[====[StarMade]====], [====[starmade]====]}
}
applicationsmenu[40] = {
{[====[Feh]====], [====[feh %F]====]},
{[====[GNU Image Manipulation Program]====], [====[gimp-2.8]====]},
{[====[Gpick]====], [====[gpick]====]},
{[====[Mirage]====], [====[mirage %f]====]},
{[====[New Drawing]====], [====[inkscape]====]},
{[====[Pinta]====], [====[pinta %F]====]}
}
applicationsmenu[50] = {
{[====[Avahi SSH Server Browser]====], [====[/usr/bin/bssh]====]},
{[====[Avahi VNC Server Browser]====], [====[/usr/bin/bvnc]====]},
{[====[Dropbox]====], [====[dropboxd]====]},
{[====[Links]====], [====[xlinks -g]====]},
{[====[Open address book]====], [====[thunderbird -addressbook]====]},
{[====[Open Safe Mode]====], [====[hexchat --no-auto --no-plugins]====]},
{[====[Opera]====], [====[/home/haron/lib/opera/opera]====]},
{[====[Opera]====], [====[/home/haron/lib/opera/opera]====]},
{[====[Psi]====], [====[psi]====]},
{[====[Start-Tor-Browser]====], [====[/home/haron/lib/tor-browser_ru/start-tor-browser]====]},
{[====[Telegram Desktop]====], [====[telegram-desktop -- %u]====]},
{[====[Telegram Desktop]====], [====[-- %u]====]},
{[====[Tixati]====], [====[tixati]====]},
{[====[Tixati]====], [====[/usr/bin/tixati]====]},
{[====[Viber]====], [====[viber]====]},
{[====[Viber]====], [====[/opt/viber/Viber]====]},
{[====[Vivaldi (snapshot)]====], [====[/usr/bin/vivaldi-snapshot]====]},
{[====[Zenmap]====], [====[zenmap %F]====]},
{[====[Zenmap (as root)]====], [====[/usr/share/zenmap/su-to-zenmap.sh %F]====]}
}
applicationsmenu[60] = {
{[====[Math]====], [====[libreoffice --math]====]},
{[====[New Database]====], [====[libreoffice --base]====]},
{[====[New Document]====], [====[libreoffice --writer]====]},
{[====[New Drawing]====], [====[libreoffice --draw]====]},
{[====[New Formula]====], [====[libreoffice --math]====]},
{[====[New Presentation]====], [====[libreoffice --impress]====]},
{[====[New Spreadsheet]====], [====[libreoffice --calc]====]},
{[====[WPS Presentation]====], [====[/usr/bin/wpp %f]====]},
{[====[WPS Spreadsheets]====], [====[/usr/bin/et %f]====]},
{[====[WPS Writer]====], [====[/usr/bin/wps %f]====]}
}
applicationsmenu[70] = {
{[====[2D-Place]====], [====[/home/haron/bin/2D-Place]====]},
{[====[A Wine application]====], [====[env WINEPREFIX="/home/haron/prefix32" wine start /ProgIDOpen VBSFile %f]====]},
{[====[Access Prompt]====], [====[/usr/lib/gcr/gcr-prompter]====]},
{[====[Acestream Launcher]====], [====[/usr/bin/acestream-launcher %u]====]},
{[====[Daily]====], [====[/home/haron/lib/thunderbird/thunderbird]====]},
{[====[Deadbeef-portable]====], [====[/home/haron/lib/deadbeef/deadbeef]====]},
{[====[feh-scale]====], [====[feh -. %f]====]},
{[====[feh-scale]====], [====[feh -. %f]====]},
{[====[Firefox]====], [====[/home/haron/lib/firefox-beta/firefox %u]====]},
{[====[Firefox]====], [====[/home/haron/lib/firefox-esr/firefox %u]====]},
{[====[FoxitReader]====], [====[/home/haron/.local/bin/FoxitReader %f]====]},
{[====[Geoclue Demo agent]====], [====[/usr/lib/geoclue2/geoclue-2.0/demos/agent]====]},
{[====[Gis-Weather]====], [====[python /home/haron/lib/gis-weather-0.7.5/gis-weather.py]====]},
{[====[Google Keep – заметки и списки]====], [====[/opt/vivaldi-snapshot/vivaldi-snapshot]====]},
{[====[Google Keep – заметки и списки]====], [====[/usr/bin/chromium --profile-directory=Default --app-id=hmjkmjkepdijhoojdojkdfohbdgmmhki]====]},
{[====[HMM3]====], [====[/home/haron/lib/hmm3/heroes3]====]},
{[====[i3]====], [====[i3]====]},
{[====[LibreOffice XSLT based filters]====], [====[libreoffice]====]},
{[====[Open Folder]====], [====[pcmanfm-mod]====]},
{[====[Pocket]====], [====[/usr/bin/chromium --profile-directory=Default --app-id=mjcnijlhddpbdemagnpefmlkjdagkogk]====]},
{[====[PRO100]====], [====[wine /home/haron/lib/Pro100-5.20-GIV/PRO100.exe %f]====]},
{[====[PRO100]====], [====[wine /home/haron/lib/Pro100-5.20-GIV/PRO100.exe %f]====]},
{[====[PRO100 4.42]====], [====[env WINEPREFIX="/home/haron/.wine" wine '/home/haron/lib/PRO100/pro100.exe']====]},
{[====[PRO100 5.20]====], [====[env WINEPREFIX="/home/haron/.wine" wine '/home/haron/lib/Pro100-5.20-GIV/PRO100.exe']====]},
{[====[subl3]====], [====[subl3]====]},
{[====[thunderbird]====], [====[/home/haron/.local/bin/thunderbird %f]====]},
{[====[transgui]====], [====[transgui %f]====]},
{[====[View file]====], [====[/usr/bin/gcr-viewer]====]},
{[====[Where am I?]====], [====[/usr/lib/geoclue2/geoclue-2.0/demos/where-am-i]====]},
{[====[Wine Installer]====], [====[env WINEPREFIX="/home/haron/prefix32" wine start /ProgIDOpen Msi.Patch %f]====]},
{[====[Wine Windows Program Loader]====], [====[wine start /unix %f]====]},
{[====[winebrowser]====], [====[env WINEPREFIX="/home/haron/.wine" wine start /ProgIDOpen pdffile %f]====]},
{[====[xmicro]====], [====[xmicro %f]====]},
{[====[xvim]====], [====[xvim %f]====]},
{[====[Платежная система Интернет-магазина Chrome]====], [====[/usr/bin/chromium --profile-directory=Default --app-id=nmmhkkegccagdldgiimedpiccmgmieda]====]}
}
